// Code generated by cmd/wiregen -upstream 78a7ab4ed6754a694a7699091e03f5f9bfee45d9; DO NOT EDIT.
// Source: backend/internal/registry/testdata/upstream/freebuff-models.ts
// (plus freebuff-model-ids.ts, freebuff-model-entitlements.ts, model-config.ts)
// at upstream commit 78a7ab4ed6754a694a7699091e03f5f9bfee45d9.
package modelcat

import (
	"time"
)

// ModelInfo describes one catalog model and every proxy fact about it.
type ModelInfo struct {
	// ID is the wire model id (provider/model).
	ID string
	// DisplayName is the upstream catalog display name (used in the
	// withdrawn-model refusal copy, mirroring freebuffWithdrawnModelMessage).
	DisplayName string
	// Served gates /v1/models and the chat handlers: the ids this gateway
	// serves or advertises. Paused models are never Served.
	Served bool
	// PausedReplacement is non-empty exactly when upstream
	// FREEBUFF_PAUSED_FREE_MODEL_IDS lists the model: recognized but
	// admission-refused. It names the model the refusal copy recommends.
	PausedReplacement string
	// Premium marks FREEBUFF_PREMIUM_MODEL_IDS membership (the shared daily
	// premium pool). Fable 5 is premium-flagged upstream but metered by its
	// own global pool (FREEBUFF_LIMITED_OFFER_MODEL_IDS), not the shared
	// pool, so it is NOT marked Premium here.
	Premium bool
	// ContextWindow mirrors FREEBUFF_MODEL_CONTEXT_WINDOWS in tokens; 0
	// means upstream falls back to DefaultContextWindow.
	ContextWindow int
	// Efforts is the upstream reasoning-effort ladder (nil = route accepts
	// and ignores reasoning_effort, so conversion uses the default ladder).
	Efforts []string
	// Tagline is the upstream catalog description (used in picker & catalog).
	Tagline string
	// Notice is the upstream warning or special offer (e.g. AI training, promo).
	Notice string
	// Badges are the capability/freshness chips (e.g. Reasoning: max*, Images, NEW).
	Badges []string
}

// Catalog is the full free-catalog table, in upstream SUPPORTED_FREEBUFF_MODELS
// order.
var Catalog = []ModelInfo{
	{ID: "stealth/ox-alpha", DisplayName: "Ox Alpha",
		ContextWindow:     1000000,
		Efforts:           []string{"low", "high", "max"},
		PausedReplacement: "z-ai/glm-5.3-flash"},
	{ID: "deepseek/deepseek-v4-pro", DisplayName: "DeepSeek V4 Pro",
		ContextWindow:     1048576,
		Efforts:           []string{"low", "high", "max"},
		PausedReplacement: "z-ai/glm-5.3-flash"},
	{ID: "minimax/minimax-m3", DisplayName: "MiniMax M3",
		ContextWindow:     524288,
		Efforts:           []string{"high"},
		PausedReplacement: "z-ai/glm-5.3-flash"},
	{ID: "openai/gpt-5.6-luna", DisplayName: "GPT-5.6 Luna",
		Tagline:       "Strong all-around",
		Badges:        []string{"Reasoning: high", "Images"},
		Served:        true,
		Premium:       true,
		ContextWindow: 1000000,
		Efforts:       []string{"low", "medium", "high", "xhigh", "max"}},
	{ID: "upstage/solar-pro4", DisplayName: "Solar Pro 4",
		Tagline:       "0 Freebucks",
		Served:        true,
		ContextWindow: 500000},
	{ID: "google/gemini-3.8-flash", DisplayName: "Gemini 3.8 Flash",
		Efforts: []string{"low", "medium", "high", "xhigh", "max"}},
	{ID: "meta/muse-spark-1.3-contributor", DisplayName: "Muse Spark 1.3",
		Tagline:           "Queues, then falls back",
		Badges:            []string{"Reasoning: xhigh", "NEW"},
		Notice:            "May use data for AI training",
		ContextWindow:     1000000,
		Efforts:           []string{"minimal", "low", "medium", "high", "xhigh"},
		PausedReplacement: "z-ai/glm-5.3-flash"},
	{ID: "meta/muse-spark-1.2-contributor", DisplayName: "Muse Spark 1.2",
		Tagline:       "Queue",
		Badges:        []string{"Reasoning: xhigh"},
		Notice:        "May use data for AI training",
		Served:        true,
		Premium:       true,
		ContextWindow: 1000000,
		Efforts:       []string{"minimal", "low", "medium", "high", "xhigh"}},
	{ID: "z-ai/glm-5.2", DisplayName: "GLM 5.2",
		Tagline:           "Referral reward",
		Badges:            []string{"Referral only"},
		Notice:            "Unlocked via referral code",
		PausedReplacement: "z-ai/glm-5.3-flash"},
	{ID: "z-ai/glm-5.3-flash", DisplayName: "GLM 5.3 Flash",
		Tagline:       "Deep reasoning",
		Badges:        []string{"Reasoning: max*", "Images", "NEW"},
		Served:        true,
		ContextWindow: 1000000,
		Efforts:       []string{"low", "high", "max"}},
	{ID: "deepseek/deepseek-v4-flash", DisplayName: "DeepSeek V4 Flash 07/31",
		Tagline:       "Smart & Fast",
		Badges:        []string{"Reasoning: high", "NEW"},
		Notice:        "May use data for AI training",
		Served:        true,
		ContextWindow: 1048576,
		Efforts:       []string{"low", "high", "max"}},
	{ID: "mimo/mimo-v2.5", DisplayName: "MiMo 2.5",
		Tagline: "Balanced",
		Badges:  []string{"Images"},
		Served:  true,
		Efforts: []string{"high"}},
	{ID: "anthropic/claude-fable-5", DisplayName: "Claude Fable 5",
		Efforts: []string{"low", "medium", "high", "xhigh", "max"}},
}

// DefaultModelID mirrors upstream DEFAULT_FREEBUFF_MODEL_ID
// (FREEBUFF_MODELS[0]): what the upstream CLI resolves a blank model pick
// to, and what paused-model refusals recommend.
const DefaultModelID = "z-ai/glm-5.3-flash"

// FallbackModelID mirrors upstream FALLBACK_FREEBUFF_MODEL_ID: the model
// guaranteed available on EVERY tier that unavailable picks are coerced to.
const FallbackModelID = "mimo/mimo-v2.5"

// LimitedModelID is the proxy limited-tier admission row: the unlimited
// fallback row, pinned to FALLBACK (not to upstream LIMITED_FREEBUFF_MODEL_ID,
// which upstream split from the picker hero on 2026-09-07 into a coercion
// target of its own). The server gate admits only this row without quota, so
// following upstream here would widen limited-tier admission; revisit
// deliberately, never on sync.
const LimitedModelID = "mimo/mimo-v2.5"

// DeepSeekV4FlashModelID mirrors upstream FREEBUFF_DEEPSEEK_V4_FLASH_MODEL_ID.
const DeepSeekV4FlashModelID = "deepseek/deepseek-v4-flash"

// LimitedTierModelIDs mirrors upstream LIMITED_FREEBUFF_MODEL_IDS: the four models
// available to limited-access tier accounts (GLM 5.3 Flash, DeepSeek V4 Flash,
// MiMo 2.5, Solar Pro 4).
var LimitedTierModelIDs = []string{
	Glm53ModelID,
	DeepSeekV4FlashModelID,
	LimitedModelID,
	SolarPro4ModelID,
}

// IsLimitedTierAllowed reports whether the model is available on the limited tier
// without requiring special referral grants (matches upstream LIMITED_FREEBUFF_MODEL_IDS).
func IsLimitedTierAllowed(id string) bool {
	switch id {
	case Glm53ModelID, DeepSeekV4FlashModelID, LimitedModelID, SolarPro4ModelID:
		return true
	default:
		return false
	}
}

// Glm52ModelID is the referral-reward model, metered by its own promo pool
// rather than the shared premium pool.
const Glm52ModelID = "z-ai/glm-5.2"

// Glm53ModelID is the unmetered standard row and the proxy default.
const Glm53ModelID = "z-ai/glm-5.3-flash"

// SolarPro4ModelID mirrors FREEBUFF_SOLAR_PRO_4_MODEL_ID: the Upstage row,
// unmetered at full access (entitlement fullAccess.premium=false).
const SolarPro4ModelID = "upstage/solar-pro4"

// GLMSessionLength mirrors upstream FREEBUFF_REWARD_SESSION_LENGTH_MS (the
// earned-reward session pool GLM 5.2 admits from; the older
// FREEBUFF_GLM_V52_SESSION_LENGTH_MS name is gone upstream): GLM sessions
// are exactly one hour of wall-clock time.
const GLMSessionLength = time.Hour

// DefaultContextWindow mirrors upstream FREEBUFF_DEFAULT_CONTEXT_WINDOW:
// assumed for any model absent from FREEBUFF_MODEL_CONTEXT_WINDOWS.
const DefaultContextWindow = 131072
