// Code generated by cmd/wiregen -upstream 2e57674fc24e8f857cd9e4f8c690f10e6e5342d1; DO NOT EDIT.
// Notice copy at upstream commit 2e57674fc24e8f857cd9e4f8c690f10e6e5342d1, extracted verbatim from
// common/src/constants/freebuff-spend-ceilings.ts,
// common/src/util/freebuff-model-availability.ts, and
// common/src/constants/freebuff-peak-hours.ts. A reworded notice or moved
// peak window fails the generator explicitly.
package upstream

const (
	// TierChangeNotice is FREEBUFF_TIER_CHANGE_NOTICE from upstream. Upstream FREEBUFF_TIER_CHANGE_NOTICE (common/src/util/freebuff-model-availability.ts).
	TierChangeNotice = "Solar Pro 4 is now unmetered at full access and available with limited access. GPT-5.6 Luna still uses your shared premium allowance, charging partial time rounded up to a tenth. —❤️ Freebuff Team"
	// CapacityNotice is FREEBUFF_CAPACITY_NOTICE. Upstream FREEBUFF_CAPACITY_NOTICE (common/src/constants/freebuff-spend-ceilings.ts).
	CapacityNotice = "Capacity is now limited per account — sustained automated abuse forced us to cap how much any one account can use."
	// RestrictedNotice is FREEBUFF_RESTRICTED_NOTICE. Upstream FREEBUFF_RESTRICTED_NOTICE (common/src/constants/freebuff-spend-ceilings.ts).
	RestrictedNotice = "This account has reduced capacity: it was flagged for VPN or proxy usage, a restricted location, or an email domain commonly used by bot farms. If you are on a VPN, connecting directly restores normal limits."
	// BudgetNotice is FREEBUFF_BUDGET_NOTICE. Upstream FREEBUFF_BUDGET_NOTICE (common/src/constants/freebuff-spend-ceilings.ts).
	BudgetNotice = "You have used all of today’s free usage on this account."
	// FreebucksCeilingNotice is FREEBUFF_FREEBUCKS_CEILING_NOTICE. Upstream retired the per-model caps to soft pacing targets; the spend field itself is @deprecated on the wire. Upstream FREEBUFF_FREEBUCKS_CEILING_NOTICE (common/src/constants/freebuff-spend-ceilings.ts).
	FreebucksCeilingNotice = "This account hit today’s hard usage cap. Freebucks pay for sessions, but the compute a day can draw is capped at three times what its Freebucks are worth, to protect the service from runaway usage."

	// DeepSeekExpensiveWindowStartUTC and DeepSeekExpensiveWindowEndUTC bound
	// the single weekday window [start, end) UTC in which DeepSeek is most
	// expensive: min(DEEPSEEK_PEAK_HOUR_RANGES_UTC starts) minus
	// DEEPSEEK_EXPENSIVE_WINDOW_LEAD_HOURS through max(ends).
	DeepSeekExpensiveWindowStartUTC = 0
	DeepSeekExpensiveWindowEndUTC   = 10
	// DeepSeekExpensiveWindowLeadHours is how long before peak opens the
	// admission window starts standing sessions off.
	DeepSeekExpensiveWindowLeadHours = 1
)

// DeepSeekPeakHourRangesUTC mirrors DEEPSEEK_PEAK_HOUR_RANGES_UTC: the
// half-open [start, end) UTC pricing windows behind the expensive window.
var DeepSeekPeakHourRangesUTC = [][2]int{{1, 4}, {6, 10}}
