package upstream

import (
	"fmt"
	"time"
)

// Upstream static notices and announcement strings from CodebuffAI/freebuff.
// The constants live in notices_gen.go (generated by cmd/wiregen from the
// pinned snapshots); the peak-window evaluation below consumes the generated
// DeepSeekExpensiveWindow* constants so the window cannot drift from billing.

// DeepSeekPeakHoursWindow holds the live evaluation of DeepSeek pricing windows
// (common/src/constants/freebuff-peak-hours.ts: DEEPSEEK_EXPENSIVE_WINDOW_UTC [0, 10]).
type DeepSeekPeakHoursWindow struct {
	IsPeak         bool      `json:"is_peak"`
	CurrentUTC     string    `json:"current_utc"`
	WindowStartUTC string    `json:"window_start_utc"`
	WindowEndUTC   string    `json:"window_end_utc"`
	NextWindowAt   time.Time `json:"next_window_at"`
	NextWindowIn   string    `json:"next_window_in"`
}

// EvaluateDeepSeekPeak determines whether the given time falls within
// DeepSeek's weekday peak pricing window (00:00 UTC - 10:00 UTC, Mon-Fri).
func EvaluateDeepSeekPeak(now time.Time) DeepSeekPeakHoursWindow {
	utc := now.UTC()
	weekday := utc.Weekday()
	hour := utc.Hour()

	isWeekday := weekday >= time.Monday && weekday <= time.Friday
	isPeakHour := hour >= DeepSeekExpensiveWindowStartUTC && hour < DeepSeekExpensiveWindowEndUTC
	isPeak := isWeekday && isPeakHour

	var next time.Time
	if isPeak {
		// Window ends today at 10:00 UTC
		next = time.Date(utc.Year(), utc.Month(), utc.Day(), DeepSeekExpensiveWindowEndUTC, 0, 0, 0, time.UTC)
	} else {
		// Next window starts tomorrow at 00:00 UTC, or Monday if weekend
		nextDay := utc.Add(24 * time.Hour)
		next = time.Date(nextDay.Year(), nextDay.Month(), nextDay.Day(), DeepSeekExpensiveWindowStartUTC, 0, 0, 0, time.UTC)
		for next.Weekday() == time.Saturday || next.Weekday() == time.Sunday {
			next = next.Add(24 * time.Hour)
		}
	}

	remaining := next.Sub(utc).Round(time.Minute)
	remStr := remaining.String()

	return DeepSeekPeakHoursWindow{
		IsPeak:         isPeak,
		CurrentUTC:     utc.Format("15:04 UTC"),
		WindowStartUTC: fmt.Sprintf("%02d:00 UTC", DeepSeekExpensiveWindowStartUTC),
		WindowEndUTC:   fmt.Sprintf("%02d:00 UTC", DeepSeekExpensiveWindowEndUTC),
		NextWindowAt:   next,
		NextWindowIn:   remStr,
	}
}
