// The upstream body-code vocabulary as typed constants. The WireCode const
// block lives in wirecodes_gen.go (generated by cmd/wiregen from the pinned
// snapshots); classifyError matches on the constants, so the wire vocabulary
// lives in one place.
package upstream

// WireCode is an upstream refusal/body marker. It is a string, so it is
// directly comparable and usable anywhere a body marker is matched.
type WireCode string
