// Code generated by cmd/wiregen -upstream 78a7ab4ed6754a694a7699091e03f5f9bfee45d9; DO NOT EDIT.
// Wire vocabulary at upstream commit 78a7ab4ed6754a694a7699091e03f5f9bfee45d9: snapshot-backed values are
// extracted from common/src/types/freebuff-session.ts (status literals and
// FREEBUFF_GATE_CODES) and cross-checked on every run; the remaining body
// markers are pinned server-observed refusal strings absent from the
// snapshots. A new status/gate literal fails the generator explicitly.
package upstream

const (
	// WireCodeDeploymentOutsideHours: free tier is outside operating hours.
	// pinned server-observed body marker (absent from the snapshots).
	WireCodeDeploymentOutsideHours WireCode = "deployment_outside_hours"
	// WireCodeFreeModeRunFanout: the account's concurrent-run counter looked like proxy fanout. Also the RateLimitError.Status for the refusal.
	// pinned server-observed body marker (absent from the snapshots).
	WireCodeFreeModeRunFanout WireCode = "free_mode_run_fanout"
	// WireCodeFreeModeCapacityDeferred: free-tier transient capacity queue.
	// pinned server-observed body marker (absent from the snapshots).
	WireCodeFreeModeCapacityDeferred WireCode = "free_mode_capacity_deferred"
	// WireCodeSessionLimitReached: the ACCOUNT is over its concurrent-tab budget (409).
	// snapshot: common/src/types/freebuff-session.ts.
	WireCodeSessionLimitReached WireCode = "session_limit_reached"
	// WireCodeFreeModeCLIRequired: the request lacked the CLI envelope.
	// pinned server-observed body marker (absent from the snapshots).
	WireCodeFreeModeCLIRequired WireCode = "free_mode_cli_required"
	// WireCodeCountryBlocked: free mode not available from the egress region.
	// snapshot: common/src/types/freebuff-session.ts.
	WireCodeCountryBlocked WireCode = "country_blocked"
	// WireCodeIpCapped: too many distinct users on the egress IP.
	// snapshot: common/src/types/freebuff-session.ts.
	WireCodeIpCapped WireCode = "ip_capped"
	// WireCodeWaitingRoomQueued: transient admission race.
	// snapshot: common/src/types/freebuff-session.ts.
	WireCodeWaitingRoomQueued WireCode = "waiting_room_queued"
	// WireCodeWaitingRoomRequired: the account must walk the pre-session ad-chain + streak flow (428).
	// snapshot: common/src/types/freebuff-session.ts.
	WireCodeWaitingRoomRequired WireCode = "waiting_room_required"
	// WireCodeSessionModelMismatch: the session row is bound to a different model (with a "limited" marker for the egress-IP case).
	// snapshot: common/src/types/freebuff-session.ts.
	WireCodeSessionModelMismatch WireCode = "session_model_mismatch"
	// WireCodeFreeModeInvalidAgentModel: the (agent, model) pair is not in the allowlist. Also the RateLimitError.Status for the refusal.
	// pinned server-observed body marker (absent from the snapshots).
	WireCodeFreeModeInvalidAgentModel WireCode = "free_mode_invalid_agent_model"
	// WireCodeSessionSuperseded: another instance took over the account (409).
	// snapshot: common/src/types/freebuff-session.ts.
	WireCodeSessionSuperseded WireCode = "session_superseded"
	// WireCodeTurnSpendLimit: upstream killed a runaway turn (429 per-turn spend ceiling, usually a stuck agent loop).
	// pinned server-observed body marker (absent from the snapshots).
	WireCodeTurnSpendLimit WireCode = "turn_spend_limit"
	// WireCodeFreebuffUpdateRequired: the CLI app version is out of date.
	// pinned server-observed body marker (absent from the snapshots).
	WireCodeFreebuffUpdateRequired WireCode = "freebuff_update_required"
	// WireCodeSessionExpired: the free session has expired.
	// snapshot: common/src/types/freebuff-session.ts.
	WireCodeSessionExpired WireCode = "session_expired"
	// WireCodeModelLocked: the model is locked for this account.
	// snapshot: common/src/types/freebuff-session.ts.
	WireCodeModelLocked WireCode = "model_locked"
	// WireCodeFreeModeLegacyLunaAgent: the legacy Luna agent id was used.
	// pinned server-observed body marker (absent from the snapshots).
	WireCodeFreeModeLegacyLunaAgent WireCode = "free_mode_legacy_luna_agent"
	// WireCodeFreeModeLegacyLuna: the legacy Luna id was used.
	// pinned server-observed body marker (absent from the snapshots).
	WireCodeFreeModeLegacyLuna WireCode = "free_mode_legacy_luna"
	// WireCodeRunIDNotFound: the run id is gone.
	// pinned server-observed body marker (absent from the snapshots).
	WireCodeRunIDNotFound WireCode = "runid not found"
	// WireCodeRunIDNotRunning: the run is not running.
	// pinned server-observed body marker (absent from the snapshots).
	WireCodeRunIDNotRunning WireCode = "runid not running"
	// WireCodeInsufficientQuota: upstream load saturation (the body marker for a load-shedding refusal).
	// pinned server-observed body marker (absent from the snapshots).
	WireCodeInsufficientQuota WireCode = "insufficient_quota"
	// WireCodeLimitBurstRate: burst-rate cap hit (another load-shedding body marker).
	// pinned server-observed body marker (absent from the snapshots).
	WireCodeLimitBurstRate WireCode = "limit_burst_rate"
	// WireCodePeakHours: peak-hours cap ("peak hours" body marker).
	// pinned server-observed body marker (absent from the snapshots).
	WireCodePeakHours WireCode = "peak hours"
	// WireCodePeakHoursStatus is the RateLimitError.Status for the peak-hours refusal (underscore form).
	// pinned server-observed body marker (absent from the snapshots).
	WireCodePeakHoursStatus WireCode = "peak_hours"
	// WireCodeLoadShedding is the RateLimitError.Status for a load-shedding refusal (the body markers are insufficient_quota / limit_burst_rate).
	// pinned server-observed body marker (absent from the snapshots).
	WireCodeLoadShedding WireCode = "load_shedding"
	// WireCodeRateLimited: generic rate limit.
	// snapshot: common/src/types/freebuff-session.ts.
	WireCodeRateLimited WireCode = "rate_limited"
	// WireCodeSpendLimited: spend ceiling reached.
	// snapshot: common/src/types/freebuff-session.ts.
	WireCodeSpendLimited WireCode = "spend_limited"
	// WireCodeBanned: the account is temporarily banned (the canonical {"status":"banned"} marker).
	// snapshot: common/src/types/freebuff-session.ts.
	WireCodeBanned WireCode = "banned"
	// WireCodeAccountSuspended: hard-ban shape ({"error":"account_suspended",...}).
	// pinned server-observed body marker (absent from the snapshots).
	WireCodeAccountSuspended WireCode = "account_suspended"
)
