// Code generated by cmd/wiregen -upstream af898dcad679dbbd27389aef8a674cee31d58d43; DO NOT EDIT.
// Snapshots: backend/internal/wirefacts/testdata/wire/snapshots.json at
// upstream commit af898dcad679dbbd27389aef8a674cee31d58d43 (npm freebuff 0.0.173).
package wirefacts

// UpstreamSHA is the upstream commit the snapshots were taken from.
const UpstreamSHA = "af898dcad679dbbd27389aef8a674cee31d58d43"

// VendorVersion is the npm freebuff wrapper version recorded alongside.
const VendorVersion = "0.0.173"

// WireFiles lists the verbatim upstream wire snapshots.
var WireFiles = []WireFile{
	{Path: "common/src/constants/freebuff-standing.ts", SHA256: "555339c61867c8201bca066765f8b4497b874e62a142be9f2d30996d46b3fb32"},
	{Path: "common/src/constants/foreign-client-signals.ts", SHA256: "3639408ac5d85f9dc2defb3cf2359ad7877e9078261082b406673c26dad5f48d"},
	{Path: "common/src/constants/freebuff-spend-ceilings.ts", SHA256: "c649e9f3fc8a735a15f12991ca4340ba31ac7c765a7233f02b225982514294d7"},
	{Path: "common/src/constants/freebuff-signup-block.ts", SHA256: "b4200624750273c214c5648bd5caf23724d7e77205423aed28e162cefb7fb771"},
	{Path: "common/src/constants/freebuff-peak-hours.ts", SHA256: "8cb33dfeaf178acfd1bc8048f51b7a05962f3baca407596078daf67f70a8daea"},
	{Path: "common/src/util/freebuff-model-availability.ts", SHA256: "43971606f9410a967c321836823485c555e97d228ebffaae4f1e0b4c54a96025"},
	{Path: "cli/src/components/freebuff-model-selector.tsx", SHA256: "1c01bc7753a32214646cadc9ca63fda1befc6b80743b9e9cecb175a158ad2006"},
	{Path: "common/src/types/freebuff-session.ts", SHA256: "0815c431e906d0c4b0ac6e8e66a061c8322ee3e7e3a4a486329d8968753473a7"},
	{Path: "packages/agent-runtime/src/constants.ts", SHA256: "233ab67d19223467f665ecaa085e732d0ee478740b6bc469e029598392d949e4"},
	{Path: "packages/agent-runtime/src/prompt-agent-stream.ts", SHA256: "7bf7ca49fb51ee52e340e577c999fd8e1a402602971f5d09897c831c444eb55f"},
	{Path: "packages/agent-runtime/src/run-agent-step.ts", SHA256: "70abc659c5b9b83d3ee249561f9e2fed18ac6dec9e394f709c0268a8a58df1f1"},
	{Path: "packages/agent-runtime/src/run-programmatic-step.ts", SHA256: "ee15c9726e1ca7b68ebb67a82c8bd31d0e4b19943f03d3927185bc2cb79ef7be"},
	{Path: "common/src/tools/constants.ts", SHA256: "c2508c4590f2b8dacf72075d32a0f21099037cb4cf3a37b097fafd670bf110b9"},
}

// RegistryPins lists the registry mirror files verified with the snapshots.
var RegistryPins = []WireFile{
	{Path: "free-agents.ts", SHA256: "e2077f92c6328edaae304fe66b3cc372faa60a70bc29a338cd912f00d2357886"},
	{Path: "freebuff-model-ids.ts", SHA256: "b4a0f2aca8ea66c1d2dcbba74003f310fd95185e60839a560115068c4493409b"},
	{Path: "freebuff-models.ts", SHA256: "6eb41a9ed69776d0b69c5b06e2c9f57656f73750860530bbba776b984d3e282b"},
	{Path: "gemini.ts", SHA256: "5de5784f96331b93cccd7a4356af17de52783f1727acee17f9c5ebe390569e80"},
	{Path: "model-config.ts", SHA256: "210f9bbfe1ac249aafeb0b134c01c2725b491696130313d225803290f0b988ea"},
	{Path: "freebuff-model-entitlements.ts", SHA256: "695bf9dd0c8d50937fbd01fd127631ef4cced7427cc1595c44476d84d2fc43cb"},
}
