// Package wirefacts pins verbatim upstream wire-shape snapshots and the
// codegen contract later Wave D slices plug catalog, wirecodes, notices,
// and toolmap emission into. testdata/wire/ holds the snapshots plus a
// sha256 manifest; they are never transformed, so review-wire-drift.sh
// keeps reading the same bytes. wirefacts_gen.go is generated:
//
//	go generate ./backend/internal/wirefacts/
//
//go:generate go run ../../cmd/wiregen -upstream 78a7ab4ed6754a694a7699091e03f5f9bfee45d9
package wirefacts

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// WireFile is one pinned file: vendor-relative path plus sha256 hex of its
// verbatim bytes.
type WireFile struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
}

// RegistryFiles lists the six registry mirror files verified alongside the
// wire snapshots. Mirrors sourceFiles in backend/internal/registry/registry.go
// and REGISTRY_FILES in scripts/check-upstream.sh; keep all three in sync.
var RegistryFiles = []string{
	"free-agents.ts", "freebuff-model-ids.ts", "freebuff-models.ts",
	"gemini.ts", "model-config.ts", "freebuff-model-entitlements.ts",
}

// manifest mirrors testdata/wire/snapshots.json.
type manifest struct {
	UpstreamSHA   string     `json:"upstream_sha"`
	VendorVersion string     `json:"vendor_version"`
	Files         []WireFile `json:"files"`
}

// Run regenerates the wirefacts_gen.go source for upstreamSHA. Out receives
// nothing on error, so callers can exit fatal without emitting a half-written
// file.
func Run(upstreamSHA, wireDir, registryDir string, out io.Writer) error {
	raw, err := os.ReadFile(filepath.Join(wireDir, "snapshots.json"))
	if err != nil {
		return fmt.Errorf("wiregen: read snapshots manifest: %w", err)
	}
	var m manifest
	if err := json.Unmarshal(raw, &m); err != nil {
		return fmt.Errorf("wiregen: parse snapshots manifest: %w", err)
	}
	if upstreamSHA != m.UpstreamSHA {
		return fmt.Errorf("wiregen: -upstream %q does not match manifest upstream_sha %q (testdata/wire/snapshots.json); re-pin the snapshots before regenerating", upstreamSHA, m.UpstreamSHA)
	}
	wires := make([]WireFile, 0, len(m.Files))
	for _, f := range m.Files {
		src, err := os.ReadFile(filepath.Join(wireDir, filepath.FromSlash(f.Path)))
		if err != nil {
			return fmt.Errorf("wiregen: read wire snapshot %s: %w", f.Path, err)
		}
		if got := sha256Hex(src); got != f.SHA256 {
			return fmt.Errorf("wiregen: wire snapshot %s hash %s != manifest %s at upstream commit %s; re-pin before regenerating", f.Path, got, f.SHA256, m.UpstreamSHA)
		}
		if err := ScanTS(f.Path, src, m.UpstreamSHA); err != nil {
			return err
		}
		wires = append(wires, WireFile{Path: f.Path, SHA256: f.SHA256})
	}
	regs := make([]WireFile, 0, len(RegistryFiles))
	for _, name := range RegistryFiles {
		src, err := os.ReadFile(filepath.Join(registryDir, name))
		if err != nil {
			return fmt.Errorf("wiregen: read registry pin %s: %w", name, err)
		}
		regs = append(regs, WireFile{Path: name, SHA256: sha256Hex(src)})
	}
	src, err := format.Source(emit(m.UpstreamSHA, m.VendorVersion, upstreamSHA, wires, regs))
	if err != nil {
		return fmt.Errorf("wiregen: format generated source: %w", err)
	}
	_, err = out.Write(src)
	return err
}

// emit renders the generated file; upstreamFlag echoes -upstream so
// TestGeneratedUpToDate fails on an SHA-manifest mismatch.
func emit(upstreamSHA, vendorVersion, upstreamFlag string, wires, regs []WireFile) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by cmd/wiregen -upstream %s; DO NOT EDIT.
// Snapshots: backend/internal/wirefacts/testdata/wire/snapshots.json at
// upstream commit %s (npm freebuff %s).
package wirefacts

// UpstreamSHA is the upstream commit the snapshots were taken from.
const UpstreamSHA = %q

// VendorVersion is the npm freebuff wrapper version recorded alongside.
const VendorVersion = %q

// WireFiles lists the verbatim upstream wire snapshots.
var WireFiles = []WireFile{
`, upstreamFlag, upstreamSHA, vendorVersion, upstreamSHA, vendorVersion)
	for _, f := range wires {
		fmt.Fprintf(&b, "\t{Path: %q, SHA256: %q},\n", f.Path, f.SHA256)
	}
	b.WriteString("}\n\n// RegistryPins lists the registry mirror files verified with the snapshots.\nvar RegistryPins = []WireFile{\n")
	for _, f := range regs {
		fmt.Fprintf(&b, "\t{Path: %q, SHA256: %q},\n", f.Path, f.SHA256)
	}
	b.WriteString("}\n")
	return []byte(b.String())
}

func sha256Hex(b []byte) string {
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}

// knownOpeners are the top-level TypeScript statement openers the generator
// understands (after stripping an "export [default]" / "declare" prefix).
// Anything else at top level fails the run explicitly; later slices teach
// the generator each shape they start emitting from, one construct at a time.
var knownOpeners = map[string]bool{
	"import": true, "const": true, "let": true, "var": true, "function": true, "async": true,
	"interface": true, "type": true, "enum": true, "class": true, "abstract": true,
	"if": true, "else": true, "for": true, "while": true, "do": true, "switch": true,
	"try": true, "catch": true, "finally": true, "return": true, "throw": true,
	"break": true, "continue": true, "debugger": true, "await": true,
}

// ScanTS rejects src on a top-level construct outside knownOpeners. The scan
// is lexical — comments, strings, template literals and regex literals are
// skipped; only (), [], {} depth is tracked, plus <> depth in .ts files
// where JSX cannot occur — so a rejection names file:line, the opener, and
// the upstream commit. Nested statements are out of scope: anything inside
// brackets belongs to a top-level construct already gated on.
//
// Angle tracking assumes prettier-formatted input (as upstream ships it): a
// "<" glued to its left operand opens a generic argument list, while a
// spaced "<" is a comparison that never occurs at the top level of formatted
// code. An unclosed "<" trips the end-of-file balance check, so even a
// misread fails explicitly instead of silently skipping statements.
func ScanTS(name string, src []byte, commit string) error {
	const (
		stCode = iota
		stLine
		stBlock
		stStr // '...' or "..." (quote kept in the frame)
		stTPL
	)
	type frame struct {
		state int
		quote byte // stStr only
		depth int  // bracket depth recorded at a ${ push; } pops back to it
		expr  bool // code frame pushed by ${ inside a template literal
	}
	stack := []frame{{state: stCode}}
	depth := 0
	top := func() *frame { return &stack[len(stack)-1] }

	// angles tracks generic argument depth in .ts files (no JSX there; .tsx skips it).
	angles := strings.HasSuffix(name, ".ts")
	angleDepth := 0
	lineNo := 1
	lineDepth, lineAngle := 0, 0 // depths when the current line started
	baseCode := true
	contPrev := false          // previous code line ended mid-expression (=>, operator, comma)
	var prefix strings.Builder // code chars on this line outside strings/comments
	prevSig := byte(0)         // last significant code char (regex heuristic)
	flush := func() error {
		excused := contPrev // previous code line ended mid-expression
		defer func() {
			lineDepth, lineAngle = depth, angleDepth
			baseCode = len(stack) == 1 && stack[0].state == stCode
			contPrev = false
			if t := strings.TrimSpace(prefix.String()); t != "" {
				contPrev = endsOperator(t)
			}
			prefix.Reset()
		}()
		if !baseCode || lineDepth != 0 || lineAngle != 0 {
			return nil
		}
		code := strings.TrimSpace(prefix.String())
		if code == "" || excused {
			return nil
		}
		// Structural and expression continuations, never new constructs:
		// closers, method chains, union/intersection members, ternary arms,
		// generic closers and comma continuations.
		if strings.ContainsRune("})];,.|&?:>", rune(code[0])) || strings.HasSuffix(code, ",") {
			return nil
		}
		rest := code
		for _, kw := range []string{"export default ", "export ", "declare "} {
			if after, ok := strings.CutPrefix(rest, kw); ok {
				rest = after
				break
			}
		}
		if rest = strings.TrimSpace(rest); rest == "" || strings.ContainsRune("{*}", rune(rest[0])) {
			return nil // export list (export { A, B } / export * from ...)
		}
		word := rest
		if i := strings.IndexFunc(word, func(r rune) bool {
			return r != '_' && r != '$' && (r < 'a' || r > 'z') && (r < 'A' || r > 'Z') && (r < '0' || r > '9')
		}); i >= 0 {
			word = word[:i]
		}
		if knownOpeners[word] {
			return nil
		}
		got := word
		if got == "" {
			got = code
		}
		if len(got) > 40 {
			got = got[:40] + "…"
		}
		return fmt.Errorf("wiregen: %s:%d: unknown TypeScript construct %q at upstream commit %s — teach cmd/wiregen before regenerating", name, lineNo, got, commit)
	}
	isRegex := func() bool {
		// A / opens a regex only where a value is expected: line start or
		// after an opener/punctuation char, never after a value-ending char
		// (identifier char, digit, ), ], ', ", `).
		return prevSig == 0 || strings.ContainsRune("([,=:!&|?{};", rune(prevSig))
	}
	nl := func() error { // consume a newline in any non-code state
		if err := flush(); err != nil {
			return err
		}
		lineNo++
		return nil
	}

	i := 0
	for i < len(src) {
		c := src[i]
		var next byte
		if i+1 < len(src) {
			next = src[i+1]
		}
		switch top().state {
		case stLine:
			if c == '\n' {
				stack = stack[:len(stack)-1]
				if err := nl(); err != nil {
					return err
				}
			}
			i++
		case stBlock:
			if c == '*' && next == '/' {
				stack = stack[:len(stack)-1]
				i += 2
			} else {
				if c == '\n' {
					if err := nl(); err != nil {
						return err
					}
				}
				i++
			}
		case stStr:
			if c == '\\' {
				i += 2
			} else if c == top().quote {
				stack = stack[:len(stack)-1]
				i++
			} else {
				if c == '\n' {
					if err := nl(); err != nil {
						return err
					}
				}
				i++
			}
		case stTPL:
			if c == '\\' {
				i += 2
			} else if c == '`' {
				stack = stack[:len(stack)-1]
				i++
			} else if c == '$' && next == '{' {
				stack = append(stack, frame{state: stCode, depth: depth, expr: true})
				depth++
				i += 2
			} else {
				if c == '\n' {
					if err := nl(); err != nil {
						return err
					}
				}
				i++
			}
		default: // stCode
			if c == '/' && next == '/' {
				stack = append(stack, frame{state: stLine})
				i += 2
			} else if c == '/' && next == '*' {
				stack = append(stack, frame{state: stBlock})
				i += 2
			} else if c == '\'' || c == '"' {
				// A real quoted string always closes on its line (raw
				// newlines are illegal in '...' and "..."). An unclosed
				// quote is JSX text (Today's, don't) — a plain char.
				if sameLineClose(src, i, c) {
					stack = append(stack, frame{state: stStr, quote: c})
				} else {
					prefix.WriteByte(c)
					prevSig = c
				}
				i++
			} else if c == '`' {
				stack = append(stack, frame{state: stTPL})
				i++
			} else if c == '/' && isRegex() {
				i = skipRegex(src, i) // closing / (or end of input) plus flags
				prevSig = '/'
			} else if c == '<' && angles && next != '<' && next != '=' && prevByte(i, src) != ' ' && prevByte(i, src) != '\t' {
				angleDepth++ // generic opener (Record<...>): glued to its operand
				prefix.WriteByte(c)
				prevSig = '(' // a value follows, as after (
				i++
			} else {
				switch c {
				case '{', '(', '[':
					depth++
					prefix.WriteByte(c)
					prevSig = c
				case '}', ')', ']':
					depth--
					if f := top(); f.expr && c == '}' && depth == f.depth {
						stack = stack[:len(stack)-1]
					}
					prefix.WriteByte(c)
					prevSig = c
				case '>':
					if angles && angleDepth > 0 && prevByte(i, src) != '=' && next != '=' {
						angleDepth--
						prevSig = ')'
					} else {
						prefix.WriteByte(c)
						prevSig = c
					}
				case '\n':
					prevSig = 0
					if err := nl(); err != nil {
						return err
					}
				case ';':
					prefix.WriteByte(c)
					prevSig = c
				default:
					prefix.WriteByte(c)
					if c != ' ' && c != '\t' && c != '\r' {
						prevSig = c
					}
				}
				i++
			}
		}
	}
	if depth != 0 || angleDepth != 0 || len(stack) != 1 {
		return fmt.Errorf("wiregen: %s: unbalanced brackets at end of file (depth %d, angle depth %d) at upstream commit %s — a misread construct hid statements; teach cmd/wiregen", name, depth, angleDepth, commit)
	}
	return flush()
}

// skipRegex consumes a regex literal opening at src[i] (the /) and returns
// the index past its flags. [class] aware, \-escape aware.
func skipRegex(src []byte, i int) int {
	inClass := false
	for j := i + 1; j < len(src); {
		d := src[j]
		if d == '\\' {
			j += 2
			continue
		}
		if d == '\n' {
			return j
		}
		switch {
		case d == '[':
			inClass = true
		case d == ']':
			inClass = false
		case d == '/' && !inClass:
			j++
			for j < len(src) && src[j] >= 'a' && src[j] <= 'z' {
				j++ // flags
			}
			return j
		}
		j++
	}
	return len(src)
}

// endsOperator reports whether a trimmed code line ends mid-expression, so
// the next line is an expression continuation rather than a new construct
// (arrow body after =>, ternary arm after ? or :, operand after a binary
// operator or comma, callee after a trailing dot).
func endsOperator(line string) bool {
	return strings.ContainsRune("=|?:,([{+-*/%!~^&<>.$", rune(line[len(line)-1]))
}

// sameLineClose reports whether the quote at src[i] closes before the next
// newline (backslash escapes honored). A miss means the quote is JSX text.
func sameLineClose(src []byte, i int, quote byte) bool {
	for j := i + 1; j < len(src); j++ {
		switch src[j] {
		case '\\':
			j++
		case '\n':
			return false
		default:
			if src[j] == quote {
				return true
			}
		}
	}
	return false
}

// prevByte returns the source byte before index i, or 0 at the start.
func prevByte(i int, src []byte) byte {
	if i <= 0 {
		return 0
	}
	return src[i-1]
}
