// Code generated by cmd/wiregen -tools-out at upstream af898dcad679dbbd27389aef8a674cee31d58d43; DO NOT EDIT.
// Sources (verbatim snapshots, never edited):
//
//	common/src/tools/constants.ts (toolNameParam, endsAgentStepParam, toolXmlName)
//	common/src/constants/foreign-client-signals.ts (GENERIC_TOOL_NAMES)
//
// Session envelope verified, no code emitted:
//
//	common/src/types/freebuff-session.ts
package convert

// ToolNameParam mirrors upstream toolNameParam: the JSON key carrying the
// tool name inside a codebuff_tool_call payload.
const ToolNameParam = "cb_tool_name"

// EndsAgentStepParam mirrors upstream endsAgentStepParam: the stop sentinel
// inside a codebuff_tool_call payload, never a tool argument.
const EndsAgentStepParam = "cb_easp"

// ToolXMLName mirrors upstream toolXmlName: the canonical XML tag for
// vendor tool calls in model output.
const ToolXMLName = "codebuff_tool_call"

// GenericToolNames mirrors upstream GENERIC_TOOL_NAMES: tool names we define
// that third-party harnesses also ship, so they carry no signature weight in
// the foreign-client gate.
var GenericToolNames = map[string]bool{
	"apply_patch": true,
	"glob":        true,
	"skill":       true,
	"web_search":  true,
	"write_file":  true,
}
